version: '3.8'
services:
  app:
    platform: linux/amd64 
    build: 
      context: .
      dockerfile: Dockerfile
    image: servergo:latest
    container_name: servergo
    ports:
      - "3000:3000"