version: '3.8'
services:
  app:
    platform: linux/amd64 
    build: 
      context: .
      dockerfile: Dockerfile
    image: servergo:latest
    container_name: servergo
    environment: # Variáveis de ambiente passadas para o container
      - WEATHER_API_TOKEN=xxxxxx
    ports:
      - "3000:3000"